baseURL = 'https://hanshui.space/'
languageCode = 'zh-cn'
title = '陆寒水的博客'
theme = 'github.com/janraasch/hugo-bearblog'

# 开启 Git 自动追踪修改时间
enableGitInfo = true

[frontmatter]
  lastmod = [":git", "lastmod", "date"]

[params]
  description = "万象挂空明，秋欲三更。"
  # 强制使用 light 模式，彻底关闭深青色夜间模式！
  color_scheme = "light"
  # 引入我们的 CSS
  custom_head = '<link rel="stylesheet" href="/custom.css">'

[markup.goldmark.renderer]
  unsafe = true
